name: Lint, test and Build
on: workflow_dispatch
jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - name: Lint
        run: npm lint
      - name: Test
        run: npm test
      - name: Build
        run: npm build
        