name: Reusable
on: 
  workflow_call:
    inputs:
      arctifact-name:
        description: The name of the artifact
        required: true
        default: dist
        type: string
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/download-artifact@v3
        with:
            name: ${{ inputs.arctifact-name }}
      - name: List files
        run: ls
      - name: Output information
        run: echo "Deploying and uploading"